<?php include_once("includes/header.php"); ?>
			<div class="row visible-desktop">
				<div class="span12 main-slider"><!-- SLIDER --></div>
			</div>
		</div>
	  </div>
	</header>
	<section id="content" class="container-fluid">
	<div class="container">
		<div id="headline-page">
			<h1>Dünya'da sigortacılık</h1>
			<div id="crumbs"><a href="index.php">Anasayfa</a> / <a href="dunyada-sigortacilik.php" class="active">Dünya'da sigortacılık</a></div> 
		</div>
		
		<div class="row">
			<div class="span12">
				<p>Dünyada sigortacılığa benzer ilk uygulamalara günümüzden yaklaşık 4000 yıl önce Babiller’ de rastlanmaktadır. Zamanın ticaret merkezi durumundaki Babil’ de, kervan tüccarlarına borç veren sermayedarlar, kervanların soyulması veya fidye ödeme durumuyla karşılaşmaları halinde tüccarların borçlarını silmekte, buna karşılık borcu tüccarlardan geri aldıkları zaman, taşıdıkları riskin karşılığı olarak ana borç miktarı üzerinden bir miktar para almaktaydılar. Bu olay daha sonra Kral Hammurabi tarafından yasallaştırıldı. Hammurabi Kanunlarının en büyük özelliği haydutların saldırısına uğrayan kervanların zararlarının bütün diğer kervanlar arasında paylaşılmasını öngörmeseydi. Bu, tehlike paylaşmasının kara taşımacılığındaki ilk örneğidir. </p>
				<p>M.Ö. 600 yıllarında Hindu’ lar sigorta özelliği taşıyan kredi anlaşmaları yapmaya başladılar. Basit içerikli bu anlaşmalar, toplumlardaki sigorta düşüncesini geliştirerek sigortacılıkta ilk adımları ortaya koyması bakımından önem taşımaktadır. Bu tür kredi anlaşmaları ortaçağda da gelişerek deniz ödüncü ve nakliyat sigortalarının temelini oluşturmuşlardır.</p>
				<p>Sonraları sigortaya daha yakın uygulamalar özellikle deniz ticaretinin geliştiği yerlerde görülmektedir. İlk denizci uluslardan Kartacalılar, Romalılar, Yunanlılar arasında, geminin taşıdığı yük üzerine borç verip geminin limana varamaması riskini taşıyan ve gemi salimen limana döndüğünde, hem verdiği borç miktarını , hem de taşıdığı riziko karşılığı faiz niteliğinde önemli pay alanlar bulunmaktaydı. Alınan bu faizlerin yüksekliği Kilise tarafından hoş görülmeyip, bir süre sonra da yasaklandı. Büyük olasılıkla bu yasak, olabilecek tehlikelere karşı önceden bir prim alma biçimine, dolayısıyla da sigorta fikrinin doğmasına yol açtı.</p>
				<p>Prim esaslı sigorta yaklaşık M.S. 1250 yıllarında Venedik, Floransa ve Cenova şehirlerinde görüldü. Gene de bugünkü anlamda sigortadan söz edilebilmesi için 14. yy’ ı beklemek gerekti. Ekonomik koşulların değişmesi ile ticaret, 14. yy’ dan başlayarak çok önemli gelişmeler gösterdi. O devirde deniz ticaretinde en ileride bulunan İtalya’ da sigortaya gereksinim duyuldu ve deniz sigortası kavramı da ilk defa burada ortaya çıktı. İlk sigorta poliçesi olarak kabul edilen mukavele 23 Ekim 1347 tarihini taşımaktaydı ve İtalya’ nın Cenova Limanı’ ndan Mayorka’ ya “Santa Clara“ adlı geminin yükünü temin etmek amacıyla düzenlendi. İlk sigorta şirketi de 1424 yılında, yine Cenova şehrinde kuruldu. Sigorta konusunda ilk kanuni mevzuat ise 1435 yılında yayınlanan Barselona Fermanı’ ydı. İtalya’ daki başlangıçtan sonra, deniz sigortalarının özellikle 18. yy’ da İngiltere’ de geliştiği görülmektedir.</p>
				<p>Denizde başlayıp gelişen sigortacılık, daha sonraları hayat sigortası fikrinin doğmasına neden oldu. Gemi ve yükünün sigorta edilebilmesi, kaptan, yolcular ve tayfaların da sigorta edilebilmesi fikrini getirdi. 17.yy.’da bir İtalyan bankeri olan Tonti’nin getirdiği “Tontines” denilen sistemde, belirli kişiler biraraya gelerek, belirlenen bir süre için ortaya belirli bir para koymakta, süre sonunda hayatta kalanlar parayı aralarında paylaşmaktaydı. İnsanların çoğu, kendilerinin başkalarından daha çok yaşayacaklarına inandıklarından epey rağbet gören bu sistemde ölenlerin maddi kayba uğradıkları düşünülerek, öngörülen süreden önce ölenler için de, ölüm rizikosu karşılığı prim ödenmesi öngörüldü. Ve hayat sigortalarına bir geçiş de bu şekilde başladı.</p>
				<p>17.yy.’ın ikinci yarısı sigortacılığın gelişmesine yol açan iki önemli olaya sahne olmuştur. Bunlardan ilki sigortacılıkta istatistik metod ve tekniğinin uygulanmaya başlaması (İhtimal Hesapları), ikincisi ise 2 Eylül 1666 tarihinde Londra’da meydana gelen ve dört gün sürerek 13.000 evle 100 kilisenin kül olmasına yol açan büyük yangındır. Kara sigortalarının doğmasına neden olan bu olay, halk üzerinde büyük etki yaratıp böyle felaketlerin sonuçlarına karşı önlem alınması fikrini doğurdu. Gelişen bu fikirden hareketle 1667 yılında “ Fire Office “ (Yangın Bürosu) kurulmasından sonra 1684 yılında buna rakip bir ortaklık şeklinde ortaya çıkan ilk yangın sigorta şirketi “ Friendly Society “ faaliyete geçti. 1688 yılında İngiltere’de Lloyd’s’ un temellerinin atılmasıyla sigortacılıkta yeni bir dönem başladı. Londra’da bulunan ve Edward Lloyd adında bir kişinin işlettiği kahvehane, gemi sahipleri, iş adamları, ve tüccarların deniz ticaretine ilişkin bilgi alışverişinde bulundukları bir mekan olmuştur. Burada sefere çıkan bir gemi veya geminin yükü üzerine teminat veren kişiler, “Underwriter” sıfatıyla belgeler düzenleyerek faaliyette bulunmaya başlamışlar ve yine bu kişiler Edward Lloyd’un ölümünden sonra, kendi aralarında Lloyd’s adında bir topluluk kurmuşlardır. Lloyd’s 1871 yılında İngiltere Parlamentosunun çıkardığı bir kanunla Birlik haline getirilmiştir. Lloyd’s ilk yıllarında sadece deniz sigortaları sahasında faaliyet gösterirken sonraları kara sigortaları sahasına da geçmiş olup, günümüzde her türlü sigortanın yapılabildiği bir kuruluş haline gelmiştir. Lloyd’s, dünyada başka benzeri olmayan, tamamen kendine mahsus bir sigorta kuruluşudur. Lloyd’s bir sigorta şirketi olmayıp, sigorta teminatı veren şahısların oluşturduğu bir topluluk, bir birlik ve aynı zamanda dünya gemicilik istihbaratı konusunda bir merkezdir. Lloyd’s’ un en belirgin özelliği Lloyd’s üyelerinin bütün varlıklarıyla sorumluluk taşımaları ve hiç bir zaman sigortalı ile doğrudan temas etmemeleri, ilişkinin “Broker” denilen aracı kişi veya firmalarla temin edilmesidir. Broker’lar Lloyd’s ile çalışabilmek için buraya kaydolmakta ve müşterinin gerek sigorta gerekse tazminat alma işlerini takip etmektedirler.</p>
				<p>Modern sigortacılığın doğuşuna deniz, kara sigortacılığına yangın, kaza sigortacılığına tren kazaları ile ilişkin bireysel kazalar öncülük ederken, sanayinin gelişmesiyle yaşanan büyük teknik hasarlar, mühendislik sigortalarının gelişimine yol açmıştır.</p>
				<p>20. yüzyılın başlarında sigorta şirketleri her türlü sigorta ihtiyacına cevap verebilecek şekilde örgütlenmelerini tamamlamış kuruluşlar olarak etkin hizmet verebilecek düzeye ulaşmışlardır.</p>
				<br />
			</div>
		</div>	
					
	</div>
	</section>
</div>
<?php include_once("includes/footer.php"); ?>