<?php include_once("includes/header.php"); ?>
			<div class="row visible-desktop">
				<div class="span12 main-slider"><!-- SLIDER --></div>
			</div>
		</div>
	  </div>
	</header>
	<section id="content" class="container-fluid">
	<div class="container">
		<div id="headline-page">
			<h1>Türkiye'de sigortacılık</h1>
			<div id="crumbs"><a href="index.php">Anasayfa</a> / <a href="turkiyede-sigortacilik.php" class="active">Türkiye'de sigortacılık</a></div> 
		</div>
		
		<div class="row">	
			<div class="span12">
				<p>Türkiye’ de 19.yy’ ın ikinci yarısından önce sigortacılıktan söz etmek pek mümkün değildir. Bazı Anadolu köylerinde bu tarihten önce gereksinme halinde yardım sağlamak, halkın uğrayacağı zararı karşılamak amacıyla sendikalar kurulduğu, esnaf kuruluşlarının ölüm ve hastalık durumlarında üyelerine yardım amacıyla örgütlendikleri bilinmekteyse de bunlar gerçek anlamda sigorta olmayıp, güvenlik, yardımlaşma, sosyal dayanışma düşüncesi ile oluşturulmuş kuruluşlardı. Bunlar da birkaç köye özgü kalmış, Anadolu’ ya yayılarak bir gelişme gösterememişlerdi.. </p>
				<p>Avrupa’ daki sigorta konusunda kaydedilen önemli gelişmelere karşın, Osmanlı toplumunun sosyal özellikleri, dini ortam, mali düzen, buradaki gelişimi engelliyordu. 19. yy’ ın ikinci yarısında meydana gelen yangınlar ve bunların sonucunda uğranılan büyük hasarlar, sigorta hakkındaki olumsuz düşünceler üzerinde az da olsa etki yaptı ve sigortanın doğmasına neden oldu. Özellikle 1870 yazında Beyoğlu’ ndaki yangında ( Büyük Pera Yangını ) çok sayıda işyeri, ev, cami ve kilisenin yanması, bu bölgede de daha çok yabancı ve yabancılarla ilişkide olan zenginlerin oturması sigortanın gelişme sürecini hızlandırdı..</p>
				<p>1872 yılında İngiliz sigorta şirketleri, açtıkları temsilciliklerle Türkiye’ de ilk sigortacılık faaliyetlerini başlattılar. İngilizler’ den sonra Fransızlar da Türkiye’ ye ilgi gösterdiler ve 1878 yılında ilk Fransız şirketi faaliyetlerine başladı. Bundan sonra Alman, İtalyan, İsviçre gibi yabancı ülkelerin sigorta şirketlerinin çalışmaları ile sigortacılık genişlemeye başladı. Bu şirketler duyulan gereksinimi karşılamakla beraber, o tarihlerde sigorta şirketlerinin kuruluşunu ve sigorta faaliyetini düzenleyen devlet denetimini öngören kanunların, hatta bu konuya değinen bir hükmün dahi bulunmayışı nedeniyle tamamen denetimsiz bir biçimde çalışıyorlar, diledikleri gibi hareket edip, merkezlerinden aldıkları talimatlarla işlem yapıyorlardı. Poliçelerini İngilizce veya Fransızca düzenliyorlar, anlaşmazlık durumunda da dava mercii olarak Londra mahkemelerini veya ilgili şirket merkezinin bulunduğu yerel mahkemeleri gösteriyorlardı. Diledikleri zaman sigorta poliçelerini iptal ediyorlardı..</p>
				<p>Böylece hukuki mevzuat ve denetimden yoksun, tamamen yabancılara özgü bir çalışma alanında ilk yıllar sigorta şirketleri adlarını duyurmak, sigorta düşüncesinin yayılmasını sağlayarak portföylerini genişletmek amacıyla vaatlerini yerine getirip, hasar ödemede dürüst davrandılar. Ancak zaman geçtikçe, sigortacıların istedikleri gibi çalışmaları ve Kapitülasyonlar’ın kendilerine sağladığı geniş olanakları kullanabilmeleri, bu şirketlere Türkiye’ de kolaylıkla çok para kazanabileceği izlenimini verdi. Bu durum, kısa zamanda çok fazla sigorta şirketinin çalışmasına, sigorta ahlakının bozulmasına, haksız rekabet ve ekspertiz suistimallerine yol açtı. Dürüst tüccarlar bundan olumsuz yönde etkilenmelerine rağmen hiçbir denetim olmayışı yüzünden sigorta şirketleri uzun süre en normal yangın hasarlarını bile ödemekten kaçınıp, sigortalıların hak ve hukukunu hiçe sayan bir biçimde davranmayı sürdürdüler.</p>
				<p>Bu ortam içinde 1893 yılında Osmanlı Umum Sigorta Şirketi ilk yerli sigorta şirketi olarak çalışmaya başladı. Bunu izleyen yıllarda sigortacılığın düzene sokulabilmesi için yabancı şirketler arasında birlikte hareket etme eğilimi belirdi. 12 Temmuz 1900 tarihinde 43 tanesi yabancı olmak üzere 44 sigorta şirketi biraraya gelerek sabit bir yangın tarifesi belirlediler. Bu Türkiye’ deki ilk tarifeydi..</p>
				<p>Tarife ile birlikte, Yangın Sigorta Şirketleri’ nin Sendikası adında bir örgütün oluşturulması ve sürekli bir denetim kurulunun bulunması kararı alındı. Londra’ da bulunan Fire Office Committee’ nin emirleriyle çalışmalarını yürüten sendika tarafından, yangınlara zamanında yetişerek büyümesini önlemek, yangının nedenlerini araştırmak üzere Fasman adlı bir örgüt kuruldu. Denetim mekanizması ve içeriği geliştirildi.</p>
				<p>Sendikanın bu olumlu çalışmalarına rağmen çalışan şirketlerin tamamı sendikaya girmediler ve haksız rekabet yapmaya, alınan kararların tersine davranmaya devam ettiler. 1908 ve 1914 yıllarında kanunlarda yapılan değişiklerle yabancı şirketler kontrol altına alınmaya çalışıldı. 1914 yılındaki kanunla yabancı şirketler teminat göstermeye ve vergi vermeye zorunlu tutuldular. Sendikanın adı ise “ Türkiye’ de Çalışan Sigorta Şirketleri “ olarak değiştirildi. Bu yeniliklerle yabancı şirketler Türkler ile ortaklık kurma yoluna gittiler.</p>
				<p>Böylece Cumhuriyetin ilanına kadar tümü yerli sermaye ve teknisyenlerle işletilen bir sigorta kuruluşu bulunmadığı görülmektedir. 
Cumhuriyetin ilanıyla birlikte sigorta alanında gerek yasal, gerekse kurumlaşma açısından büyük adımlar atıldı. 1924 yılında Türkçe’yi kullanma zorunluluğu getiren yasa ile, poliçelerin İngilizce ve Fransızca düzenlenmesine son verildi ve aynı yıl Sigortacılar Kulübü kuruldu. 1927 yılında Sigortacılığın ve Sigorta Şirketlerinin Teftiş ve Murakabesi hakkındaki kanun yürürlüğe girdi. Yerli ve yabancı sigorta şirketlerinin denetlenmesi, döviz çıkışının önlenmesi amacını taşıyan bu kanunun çıkışıyla sigortacılık gelişmeye, yerli sermaye ile kurulan şirketlerin sayısı artmaya başladı. Bunu izleyen iki yıl boyunca gerekli hazırlık ve incelemelerin yapılması sonucu işletme hakkının T. İş Bankası A.Ş’ ye ait olacağı bir anonim şirket kurulmasına karar verildi. Böylece 1929 yılında Milli Reasürans T.A.Ş faaliyete geçti. Bu tarihten itibaren Türkiye’ de reasürans tekeli başladı ve ülkedeki yerli - yabancı bütün sigorta şirketleri topladıkları primlerin bir kısmını Milli Reasürans’ a devretmeye zorunlu tutuldu. Hemen hemen dünyada kurulan ilk reasürans tekeli olan Milli Re. önce çeşitli tepkiler gördüyse de suistimalleri önlemek, haksız rekabetin kakmasını ve ödemelerin zamanında yapılmasını sağlamak gibi yanlarıyla Türk sigortacılığının gelişmesinde olumlu rol oynadı, halkın sigortaya olan güvenini arttırdı.</p>
				<p>Bu gelişmelerin paralelinde 1939 yılında sigorta şirketleri Ticaret Bakanlığı’na bağlandı. Sigorta sektörünü ciddi bir biçimde ele alan 7397 sayılı Sigorta Murakabe Kanunu ise 1959 yılında yürürlüğe girdi. 1987 yılında yürürlüğe giren 3379 sayılı yasa ile 7397 sayılı yasada, yasal alandaki boşlukları doldurmak, sigorta şirketlerini mali yönden geliştirmek ve sigorta aracılarının durumunu yeniden düzenlemek amacıyla önemli ve köklü değişikler yapıldı. Bu kanun, sigorta ile ilgili organlar ve faaliyetlerini düzenleyen yönetmelikler çıkarılmasını öngörüyordu. Sigorta şirketleri Hazine ve Dış Ticaret Müsteşarlığı’ na bağlanarak mali yapının bir parçası olarak kabul edildiler. 1 Mayıs 1990 tarihinden itibaren Kaza Sigortaları ( zorunlu sigortalar hariç ), Mühendislik Sigortaları ile Zirai Sigortalarda; 1 Ekim 1990 tarihinden itibaren de Yangın ve Nakliyat sigortalarında da Serbest Tarife Sistemine geçildi.</p>
				<p>Zaman içerisinde yeni kurulan sigorta şirketlerinin sayısı artarken, sigorta taleplerinin aynı ölçüde artmaması, ayrıca prim tahsilatında yaşanan sorunlar dolayısıyla, 1993 yılından itibaren çıkarılan Kanun Hükmünde Kararnameler ile 7397 sayılı Kanunda birtakım düzenlemelere gidilmesi ihtiyacı duyuldu. 1 Ocak 1995 tarihinden itibaren sigorta primlerinin tahsili sorununa çözüm getirilmesi amacıyla, primlerin acente cari hesapları üzerinden takibi sistemi yürürlükten kaldırılarak, poliçe bazında takip sistemi uygulamaya konuldu..</p>
				<p>2000 yılında, 1999 depremlerini takiben meskenler için zorunlu hale getirilmiş bulunan deprem sigortalarını yürütmek üzere tesis edilen "Doğal Afet Sigortaları Kurumu" (kısaca DASK) Pool'u tesis edilerek yönetimi beş yıllık bir süre ile bu konuda deneyimli Millî Reasürans T.A.Ş.ne verildi. Diğer taraftan Türkiye'de 23.07.1927 tarih ve 1160 sayılı Yasa ile şekillendirilmiş zorunlu reasürans devri 31.12.2001'de sona erdi..</p>
				<p>28 Mart 2001 tarihinde kabul edilen “Bireysel Emeklilik Tasarruf ve Yatırım Sistemi Kanunu” ile kurulan bireysel emeklilik sistemi 27 Ekim 2003 yılında faaliyete geçti..</p>
				<p>30.09.2004 tarihi itibariyle, ülkemizde toplam 47 sigorta şirketi faaliyette bulunmaktadır. Bunların 40’ı özel, 2’si kamu şirketi, 5’i Türkiyede kurulu yabancı şirkettir. Şirketlerin 9’u hayat, 10’u hayat/emeklilik, 1’i emeklilik, 15’i hayat-dışı, 12’si ise kompozit şirkettir. Halihazırda 15 şirketin faaliyeti durdurulmuş ve bu şirketlerden 5’i de iflas etmiştir..</p>
				<p>Türkiye’de kurulu reasürans şirketi sayısı ise 3’tür. Ancak bunlardan ikisi prim üretimini durdurmuş olduğundan faal reasürans şirket sayısı 1 olmuştur. Ayrıca, bir reasürans şirketinin de tasfiyesine izin verilmiştir.</p>
				<br />
			</div>
		</div>	
					
	</div>
	</section>
</div>
<?php include_once("includes/footer.php"); ?>